services:
  - type: web
    name: books-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /api/v1/books 